project:
  type: book
  output-dir: docs

book:
  title: "ChatGPT Personal Log"
  author: "Yuan Tian"
  cover-image: cover.png
  date: "07/18/2024"
  search: true
  repo-url: "https://github.com/tianyuan09/chatgpt-usecases"
  sidebar:
    style: "floating" # docked or floating
  chapters:
    - index.qmd
    - korean.qmd
    - linearalgebra.qmd
    - intro.qmd
    - references.qmd

comments:
  hypothesis: true

bibliography: references.bib

format:
  html:
    theme: 
      light: cerulean
      dark: darkly
    # good choices: lumen,zephyr
    # https://quarto.org/docs/output-formats/html-themes.html
    fontsize: 1em
    linestretch: 1.2
    grid:
      sidebar-width: 300px
      body-width: 1000px
      margin-width: 500px
      gutter-width: 1.5rem
    # customize component widths
    # https://quarto.org/docs/output-formats/page-layout.html#customizing-component-widths



